A	.gitignore
A	index.html
M	package-lock.json
M	package.json
M	public/assets/backgrounds/day/bg_city_day_loop.png
M	public/assets/backgrounds/day/blok_m_landmark.png
A	public/assets/backgrounds/day/goa_day.png
M	public/assets/backgrounds/day/lenteng_day.png
M	public/assets/backgrounds/day/ps_gacor_day.png
M	public/assets/backgrounds/day/upnvj_day.png
M	public/assets/backgrounds/night/blok_m_night_landmark.png
A	public/assets/backgrounds/night/goa_night.png
M	public/assets/backgrounds/night/lenteng_night.png
M	public/assets/backgrounds/night/ps_gacor_night.png
M	public/assets/backgrounds/night/upnvj_night.png
D	public/assets/backgrounds/ps_gacor_night.png
M	public/assets/backgrounds/sunset/bg_city_sunset_loop.png
M	public/assets/backgrounds/sunset/blok_m_sunset_landmark.png
A	public/assets/backgrounds/sunset/goa_sunset.png
M	public/assets/backgrounds/sunset/lenteng_sunset.png
M	public/assets/backgrounds/sunset/ps_gacor_sunset.png
M	public/assets/backgrounds/sunset/upnvj_sunset.png
M	src/game/audio/BgmManager.ts
A	src/game/config/dialogues.ts
M	src/game/config/worldVisuals.ts
M	src/game/scenes/JourneyScene.ts
A	src/game/ui/dialogueBubble.ts
M	src/main.ts
M	src/style.css
A	tsconfig.json
A	vite.config.ts
